# AUTOGENERATED! DO NOT EDIT! File to edit: 02_sports_generic.handlers.ipynb (unless otherwise specified).

__all__ = ['Players', 'Teams', 'Games']

# Cell

from ..base import Base_Handler
from .objects import Player, Team, Game

class Players(Base_Handler):

    def __init__(self, **kwargs):
        '''
        class should be instantiated with a list of Team object created using
        this package or with a pandas dataframe with the appropriate colums
        '''
        super().__init__(obj_class=Player, **kwargs)


# Cell

class Teams(Base_Handler):

    def __init__(self, **kwargs):
        '''
        class should be instantiated with a list of Team object created using
        this package or with a pandas dataframe with the appropriate colums
        '''
        super().__init__(obj_class=Team, **kwargs)


# Cell

class Games(Base_Handler):

    def __init__(self, **kwargs):
        '''
        class should be instantiated with a list of Team object created using
        this package or with a pandas dataframe with the appropriate colums
        '''
        super().__init__(Game, **kwargs)

    def add_swapped_games(self):
        NotImplementedError('add a swapped version of each game' \
                            'to the DataFrame')