# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Base_Object": "00_base.ipynb",
         "Base_Handler": "00_base.ipynb",
         "Team": "01_sports_generic.objects.ipynb",
         "Player": "01_sports_generic.objects.ipynb",
         "Game": "01_sports_generic.objects.ipynb",
         "Players": "02_sports_generic.handlers.ipynb",
         "Teams": "02_sports_generic.handlers.ipynb",
         "Games": "02_sports_generic.handlers.ipynb"}

modules = ["base.py",
           "sports_generic/objects.py",
           "sports_generic/handlers.py"]

doc_url = "https://armstrys.github.io/oos/"

git_url = "https://github.com/armstrys/oos/tree/main/"

def custom_doc_links(name): return None
