package:
  name: oos
  version: 0.0.2
source:
  sha256: ff17ae6533781062fb7d1b5bb7b57c7cfc621af979b3d18e41e52e85e56cd6a6
  url: https://files.pythonhosted.org/packages/63/a6/6a87220787c4f95a6cb8e801e9e235593bb20bd91fd43133f784497ccdfc/oos-0.0.2.tar.gz
about:
  dev_url: https://armstrys.github.io
  doc_url: https://armstrys.github.io
  home: https://armstrys.github.io
  license: Apache Software
  license_family: APACHE
  summary: A basic object-oriented programming framework for sports analysis
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - armstrys
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  run:
  - pip
  - python
  - packaging
  - pandas
test:
  imports:
  - oos
